### ISSUE TITLE
Merge conflict in pkgdown site

### ISSUE THREAD

**Issue by batpigandme** [poissonconsulting/tinter#1]
Hi,

Neat package! Was just checking it out, and I think there's a merge conflict that's showing up on the pkgdown site.
![merge conflict on pkgdown site](https://user-images.githubusercontent.com/831732/50086670-c4028880-01cb-11e9-8679-66be3a703596.png)

I've captured some of the lines in the source below, but I think they're all highlighted if you go to index.html for https://github.com/poissonconsulting/tinter/commit/a8f32fd5feec0f4186db5e88f8aa1d82b129359b

https://github.com/poissonconsulting/tinter/blob/a8f32fd5feec0f4186db5e88f8aa1d82b129359b/docs/index.html#L122-L148

Anyway, cool package! Looking forward to taking it for a spin.

**Comment by sebdalgarno** [comment]
thanks a lot for the heads up @batpigandme ! all fixed now.
